# Generated by Django 6.1.1 on 2026-10-04 21:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_zip', models.FileField(help_text="Zip of the script's source files. All files are public", upload_to='demos/', validators=[django.core.validators.FileExtensionValidator(['zip'])])),
                ('entry_point', models.CharField(help_text="Script to run, relative to the zip root (e.g. 'pipeline.py'), or a module name to run like 'python -m' (e.g. 'etl.pipeline').", max_length=200)),
                ('command', models.SlugField(help_text="What visitors type to run it, e.g. 'donki'.", max_length=40)),
                ('packages', models.CharField(blank=True, help_text='Comma-separated packages to install, e.g. pandas, request, matplotlib', max_length=300)),
                ('intro', models.TextField(blank=True, help_text='Option note shown above the console.')),
                ('examples', models.TextField(blank=True, help_text='One example command per line, show as clickable buttons.')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo', to='projects.project')),
            ],
        ),
    ]
