# Generated by Django 6.1.1 on 2026-10-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('envelope', 'Email'), ('twitter-x', 'X / Twitter'), ('mastodon', 'Mastodon'), ('discord', 'Discord'), ('youtube', 'YouTube'), ('globe', 'Website / other')], default='globe', max_length=20),
        ),
    ]
